instance of gcJSON as $gcJSON
{
    ResourceID = "[gcJSON]gcJSON";
    SourceInfo = "::5::5::gcJSON";
    ModuleName = "gcJSON";
    ModuleVersion = "1.0.0";
    IsSingleInstance = "Yes";
    ConfigurationName = "gcJSON";
};

instance of OMI_ConfigurationDocument
{
    Version = "2.0.0";
    MinimumCompatibleVersion = "1.0.0";
    CompatibleVersionAdditionalProperties = {"Omi_BaseResource:ConfigurationName"};
    Name = "gcJSON";
};
